"""
Constants for EON
"""

# Log levels
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"

# Error codes
ERROR_CODE_VALIDATION = "VALIDATION_ERROR"
ERROR_CODE_TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
ERROR_CODE_LLM = "LLM_ERROR"
ERROR_CODE_SESSION = "SESSION_ERROR"
ERROR_CODE_MEMORY = "MEMORY_ERROR"
ERROR_CODE_INTENT = "INTENT_ERROR"
ERROR_CODE_INTERNAL = "INTERNAL_ERROR"

# Action types
ACTION_TYPE_CALL = "call"
ACTION_TYPE_MESSAGE = "message"
ACTION_TYPE_NAVIGATE = "navigation"
ACTION_TYPE_DEVICE_CONTROL = "device_control"
ACTION_TYPE_OPEN_APP = "open_app"
ACTION_TYPE_CONNECTIVITY = "connectivity"
ACTION_TYPE_UNKNOWN = "unknown"

# Device settings
DEVICE_SETTING_BLUETOOTH = "bluetooth"
DEVICE_SETTING_WIFI = "wifi"
DEVICE_SETTING_VOLUME = "volume"
DEVICE_SETTING_BRIGHTNESS = "brightness"
DEVICE_SETTING_AIRPLANE_MODE = "airplane_mode"

# Device actions
DEVICE_ACTION_ON = "on"
DEVICE_ACTION_OFF = "off"
DEVICE_ACTION_INCREASE = "increase"
DEVICE_ACTION_DECREASE = "decrease"
DEVICE_ACTION_TOGGLE = "toggle"

# Messaging apps
MESSAGING_APP_SMS = "sms"
MESSAGING_APP_WHATSAPP = "whatsapp"
MESSAGING_APP_EMAIL = "email"
MESSAGING_APP_TELEGRAM = "telegram"
MESSAGING_APP_MESSENGER = "messenger"

# Maximum values
MAX_MESSAGE_LENGTH = 1000
MAX_CONTACT_NAME_LENGTH = 100
MAX_CONVERSATION_HISTORY = 50
MAX_CONTACTS_STORED = 1000

# Timeouts
LLM_TIMEOUT = 30
SESSION_TIMEOUT = 3600  # 1 hour
MEMORY_SAVE_INTERVAL = 300  # 5 minutes

# Retry logic
MAX_RETRIES = 3
RETRY_BACKOFF_FACTOR = 2
INITIAL_RETRY_DELAY = 1
